name: macOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    # Checks-out the repo. More at: https://github.com/actions/checkout
    - uses: actions/checkout@v2
    - name: Build project
      run: swift build
    - name: Run tests
      run: swift test
